# Generated by Django 3.2 on 2021-04-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coach_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payer_Stat',
            new_name='Player_Stat',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
