# Generated by Django 3.2 on 2021-04-24 17:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210424_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='address',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player_stat',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_score', models.IntegerField()),
                ('guest_score', models.IntegerField()),
                ('date', models.DateField(verbose_name='game date')),
                ('round', models.CharField(choices=[('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('FI', 'Final'), ('WI', 'Winner')], default='QF', max_length=2, verbose_name='round type')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='api.team')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='api.team')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='api.team')),
            ],
        ),
        migrations.AddField(
            model_name='player_stat',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.game'),
            preserve_default=False,
        ),
    ]
