# Generated by Django 3.2 on 2021-04-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_game_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='game',
            name='host',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='player_stat',
            name='game',
        ),
        migrations.RemoveField(
            model_name='player_stat',
            name='player',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Player_Stat',
        ),
    ]
