# Generated by Django 3.2 on 2021-04-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_coach_game_player_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
