# Generated by Django 3.2 on 2021-04-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='height',
        ),
        migrations.RemoveField(
            model_name='player_stat',
            name='score',
        ),
    ]
